NewsPortal_SF_Proj/NewsPortal/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework import routers

from news import views

router = routers.DefaultRouter()
router.register(r'articles', views.ArticlesViewSet, basename='articles')
router.register(r'news', views.NewsViewSet, basename='news')

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path('news/', include('news.urls')),
    path('api/', include('rest_framework.urls', namespace='rest_framework')),
    path('api/', include(router.urls)),
]

NewsPortal_SF_Proj/news/urls.py
from django.urls import path, include
# from django.views.decorators.cache import cache_page

from .views import (
    PostList, PostDetail, PostSearch, NewsEdit, NewsCreate, NewsDelete, ArticlesEdit, ArticlesCreate, ArticlesDelete,
    subscriptions
)





urlpatterns = [
    path('', PostList.as_view(), name='posts_list'),
    path('<int:pk>', PostDetail.as_view(), name='post_detail'),
    path('search/', PostSearch.as_view(), name='posts_search'),
    path('news/create/', NewsCreate.as_view(), name='news_create'),
    path('news/<int:pk>/edit/', NewsEdit.as_view(), name='news_edit'),
    path('news/<int:pk>/delete/', NewsDelete.as_view(), name='news_delete'),
    path('articles/create/', ArticlesCreate.as_view(), name='articles_create'),
    path('articles/<int:pk>/edit/', ArticlesEdit.as_view(), name='articles_edit'),
    path('articles/<int:pk>/delete/', ArticlesDelete.as_view(), name='articles_delete'),
    path('subscriptions/', subscriptions, name='subscriptions'),
    path('i18n/', include('django.conf.urls.i18n')),
]

NewsPortal_SF_Proj/news/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Sum
from django.urls import reverse
from django.core.cache import cache


class Author(models.Model):
    author = models.OneToOneField(User, on_delete=models.CASCADE)
    a_rating = models.IntegerField(default=0)

    def update_rating(self):
        p_rating = self.post_set.aggregate(postRating=Sum('p_rating'))
        p_rat = 0
        p_rat += p_rating.get('postRating')

        c_rating = self.author.comment_set.aggregate(commentRating=Sum('c_rating'))
        c_rat = 0
        c_rat += c_rating.get('commentRating')

        self.a_rating = p_rat * 3 + c_rat
        self.save()


class Category(models.Model):
    category = models.CharField(max_length=255,
                                unique=True)

    def __str__(self):
        return f'{self.category}'


class Post(models.Model):
    article = 'AR'
    news = 'NE'

    CHOOSE = [
        (article, 'Статья'),
        (news, 'Новость')
    ]

    p_author = models.ForeignKey(Author, on_delete=models.CASCADE)
    genre = models.CharField(max_length=2,
                             choices=CHOOSE,
                             default=news)
    time_in = models.DateTimeField(auto_now_add=True)
    category = models.ManyToManyField(Category, through='PostCategory')
    title = models.CharField(max_length=150)
    main_text = models.TextField()
    p_rating = models.IntegerField(default=0)

    def like(self):
        self.p_rating += 1
        self.save()

    def dislike(self):
        self.p_rating -= 1
        self.save()

    def preview(self):
        return self.main_text[:124]+'...'

    def __str__(self):
        return f'{self.title.title()}: {self.preview()}'

    def get_absolute_url(self):
        return reverse('post_detail', args=[str(self.id)])

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        cache.delete(f'post-{self.pk}')


class PostCategory(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.CharField(max_length=255)
    time_in = models.DateTimeField(auto_now_add=True)
    c_rating = models.IntegerField(default=0)

    def like(self):
        self.c_rating += 1
        self.save()

    def dislike(self):
        self.c_rating -= 1
        self.save()


class Subscription(models.Model):
    user = models.ForeignKey(
        to=User,
        on_delete=models.CASCADE,
        related_name='subscriptions',
    )
    category = models.ForeignKey(
        to='Category',
        on_delete=models.CASCADE,
        related_name='subscriptions',
    )


NewsPortal_SF_Proj/templates/articles_delete.html
{% extends 'flatpages/default.html' %}

{% load i18n %}

{% block title %}
{% trans "Удаление статьи" %}
{% endblock title %}

{% block content %}
<h1>{% trans "Удаление статьи" %}</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>{% trans "Удаляем" %} "{{ object.title }}"?</p>
    <input type="submit" value="Delete" />
</form>
{% endblock content %}

NewsPortal_SF_Proj/templates/articles_edit.html
{% extends 'flatpages/default.html' %}

{% load i18n %}

{% block title %}
{% trans "Редактирование статьи" %}
{% endblock title %}

{% block content %}
<h1>{% trans "Внесите параметры" %}</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock content %}

NewsPortal_SF_Proj/templates/news_delete.html
{% extends 'flatpages/default.html' %}

{% load i18n %}

{% block title %}
{% trans "Удаление новости" %}
{% endblock title %}

{% block content %}
<h1>{% trans "Удаление новости" %}</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>{% trans "Удаляем" %} "{{ object.title }}"?</p>
    <input type="submit" value="Delete" />
</form>
{% endblock content %}

NewsPortal_SF_Proj/templates/news_edit.html
{% extends 'flatpages/default.html' %}

{% load i18n %}

{% block title %}
{% trans "Редактирование новости" %}
{% endblock title %}

{% block content %}
<h1>{% trans "Внесите параметры" %}</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock content %}

NewsPortal_SF_Proj/templates/post.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}
{% load i18n %}

{% block title %}
{% trans "Пост" %}
{% endblock title %}


{% block content %}
    <h1>{{ post.title|censor }}</h1>
    <h3>{{ post|description_time_in }}</h3>
    <hr>
    <p>
        {{ post.main_text|censor }}
    </p>
{% endblock content %}

NewsPortal_SF_Proj/templates/post_created_email.html

<html lang="ru">
    <head>
        <title>Title</title>
    </head>
    <body>
        <h2>Привет! Новая <a href="{{link}}">статья</a> в твоих подписках!</h2>
    </body>
</html>

NewsPortal_SF_Proj/templates/posts.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}

{% load i18n %}

{% block title %}
{% trans "Посты" %}
{% endblock title %}


{% block content %}
    <h1>{% trans "Все новости" %}</h1>
    <h3>{{ post|length }}</h3>

    <a href="{% url 'posts_search' %}">{% trans "Поиск" %}</a>

    {% if perms.news.add_post %}
    <hr>
    <a href="{% url 'news_create' %}">{% trans "Добавить новость" %}</a>
    <a> / </a>
    <a href="{% url 'articles_create' %}">{% trans "Добавить статью" %}</a>
    {% endif %}
    <hr>
    {% if post %}
        <table>
            {% for p in post %}

            <tr>
                <td><a href="{% url 'post_detail' pk=p.id %}">{{ p.title|censor }}</a></td>
                <td>{{ p.time_in|date:'M d Y' }}</td>

                {% if p.genre == 'AR' %}
                <td>
                    {% if perms.news.change_post %}
                    <a> / </a>
                    <a href="{% url 'articles_edit' pk=p.id %}">{% trans "Изменить" %}</a>
                    {% endif %}
                    {% if perms.news.delete_post %}
                    <a> / </a>
                    <a href="{% url 'articles_delete' p.id %}">{% trans "Удалить" %}</a>
                    {% endif %}
                </td>

                {% else %}
                <td>
                    {% if perms.news.change_post %}
                    <a> / </a>
                    <a href="{% url 'news_edit' pk=p.id %}">{% trans "Изменить" %}</a>
                    {% endif %}
                    {% if perms.news.delete_post %}
                    <a> / </a>
                    <a href="{% url 'news_delete' p.id %}">{% trans "Удалить" %}</a>
                    {% endif %}
                </td>
                {% endif %}

            </tr>

            <tr>
                <td>{{ p.preview|censor }}<p></p></td>
            </tr>

            {% endfor %}`
        </table>
        <hr>
    {% endif %}

   {% if page_obj.has_previous %}
       <a href="?page=1">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   {{ page_obj.number }}

   {% if page_obj.has_next %}
       <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}

{% endblock content %}

NewsPortal_SF_Proj/templates/search.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}
{% load custom_tags %}
{% load i18n %}


{% block title %}
{% trans "Поиск постов" %}
{% endblock title %}


{% block content %}
    <h1>{% trans "Все новости" %}</h1>
    <h3>{{ post|length }}</h3>

    <hr>
    {% if perms.news.add_post %}
    <a href="{% url 'news_create' %}">{% trans "Добавить новость" %}</a>
    <a> / </a>
    <a href="{% url 'articles_create' %}">{% trans "Добавить статью" %}</a>
    {% endif %}

    <form action="" method="get" >
    {{ filterset.form.non_field_errors }}

    {{ filterset.form.title__icontains.errors }}
    <label for="{{ filterset.form.title__icontains.id_for_label }}">{% trans "Поиск" %}</label>
    <input
        id="{{ filterset.form.title__icontains.id }}"
        name="{{ filterset.form.title__icontains.name }}"
        class="form-control"
    >
    <label for="">{% trans "Категории" %}: </label>
    {{ filterset.form.category }}
    <p></p>
    <label for="filterset.form.time_in__gt.id_for_label">{% trans "Дата" %}: </label>
    <input
        type="datetime-local"
        id="{{ filterset.form.time_in__gt.id }}"
        name="{{ filterset.form.time_in__gt.name }}"
        value="{{ filterset.form.time_in__gt.value }}"
    />
    <input type="submit"
           class="mt-3 btn-primary"
           value="{% trans 'Найти' %}" />
    </form>
    <hr>
    {% if post %}
        <table>
            {% for p in post %}
            <tr>
                <td><a href="{% url 'post_detail' pk=p.id %}">{{ p.title|censor }}</a></td>
                <td>{{ p.time_in|date:'M d Y' }}</td>

                {% if p.genre == 'AR' %}
                <td>
                    {% if perms.news.change_post %}
                    <a> / </a>
                    <a href="{% url 'articles_edit' pk=p.id %}">{% trans "Изменить" %}</a>
                    {% endif %}
                    {% if perms.news.delete_post %}
                    <a> / </a>
                    <a href="{% url 'articles_delete' p.id %}">{% trans "Удалить" %}</a>
                    {% endif %}
                </td>

                {% else %}
                <td>
                    {% if perms.news.change_post %}
                    <a> / </a>
                    <a href="{% url 'news_edit' pk=p.id %}">{% trans "Изменить" %}</a>
                    {% endif %}
                    {% if perms.news.delete_post %}
                    <a> / </a>
                    <a href="{% url 'news_delete' p.id %}">{% trans "Удалить" %}</a>
                    {% endif %}
                </td>
                {% endif %}
            </tr>
            <tr>
                <td>{{ p.preview|censor }}<p></p></td>
            </tr>
            {% endfor %}`
        </table>
    {% endif %}

   {% if page_obj.has_previous %}
       <a href="?{% url_replace page=1 %}">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   {{ page_obj.number }}

   {% if page_obj.has_next %}
       <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}

{% endblock content %}

NewsPortal_SF_Proj/templates/subscriptions.html
{% extends 'flatpages/default.html' %}

{% load i18n %}

{% block title %}
{% trans "Подписки" %}
{% endblock title %}

{% block content %}
    {% for category in categories  %}
        <p>
            {{ category.category }}
            <form method="post">
                {% csrf_token %}
                <input type="hidden" name="category_id" value="{{ category.id }}" />

                {% if category.user_subscribed %}
                    <button disabled>{% trans "Подписаться" %}</button>
                    <button name="action" value="unsubscribe">{% trans "Отписаться" %}</button>
                {% else %}
                    <button name="action" value="subscribe">{% trans "Подписаться" %}</button>
                    <button disabled>{% trans "Отписаться" %}</button>
                {% endif %}
            </form>
        </p>
    {% endfor %}
{% endblock content %}

NewsPortal_SF_Proj/templates/weekly_posts.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2>Посты за неделю!</h2>
<ul>
  {% for post in posts %}
  <li>
      <a href="{{ link }}{{ post.get_absolute_url }}">{{ post.title }}</a>
  </li>
  {% endfor %}
</ul>
</body>
</html>